### ISSUE TITLE
When using, it seems the interface sticks at is recording a voice message.

### ISSUE THREAD

**Issue by Websteria** [minemo/text-generation-webui-barktts#2]
It takes a really long time after the two bars have generated as well. Sometimes I need to send another message before it replies to the first. Any ideas?

**Comment by minemo** [comment]
Well, the model can run really quickly on some hardware.
The original repository is a bit vague on exactly how fast/slow it can run though. 
What are the specs you're running it on?

**Comment by Websteria** [comment]
Rtx 4090Ryzen 5800x80gb ram On Apr 25, 2023, at 4:20 PM, WorksByM ***@***.***> wrote:﻿
Well, the model can run really quickly on some hardware.
The original repository is a bit vague on exactly how fast/slow it can run though.
What are the specs you're running it on?

**Comment by minemo** [comment]
Ah, it seems someone made a more put-together version of this plugin already.
Maybe check it out if you're having issues with mine: https://github.com/wsippel/bark_tts

**Comment by wiseman-timelord** [comment]
Fixed model download issues here:
https://github.com/wiseman-timelord/text-generation-webui-barktts-cache

**Comment by minemo** [comment]
@wiseman-timelord If your code is compatible/easy to integrate, do you want to create a pull-request?
