### ISSUE TITLE
Solution: Code that works with current state of Oobabooga

### ISSUE THREAD

**Issue by RandomInternetPreson** [minemo/text-generation-webui-barktts#8]
Okay I don't know if this project is dead what, there is another bark_tts project here: that too looks like it might be abandoned :C https://github.com/wsippel/bark_tts

If you want your current version of oobabooga to work with this extension, just replace the contents of your script.py file with this 

https://github.com/RandomInternetPreson/MiscFiles/blob/main/script.py

I took code from line 138:147 here: https://github.com/wsippel/bark_tts/blob/master/script.py

and edited it using this comment here: https://github.com/minemo/text-generation-webui-barktts/issues/7#issuecomment-1777961254

**Comment by minemo** [comment]
Yeah, I haven't had much time because of university recently. I'd be glad to transfer ownership/have someone fork this if they want to continue developing this though, since it seems the extension has apparently gathered some interest.

**Comment by RandomInternetPreson** [comment]
I don't know much python (I do mostly Matlab programming) and I don't know how to use git very well 😞 but I'll try forking this in a day or so for a repo that is whole for others to use.

**Comment by RandomInternetPreson** [comment]
I have forked your repo and provided an explanation of the changes I made:

https://github.com/RandomInternetPreson/text-generation-webui-barktts/commit/c1d64d91bb6b6ff87e00e3a0090870dcc8fe5736

https://github.com/RandomInternetPreson/text-generation-webui-barktts

Thank you for all of your hard work and good luck with your studies.

**Comment by minemo** [comment]
Nice, I'll add a reference to your repo in the Readme. 
Thanks for keeping the extension updated ^^
